version: 0.0
os: linux
files:
  - source: Dockerfile
    destination: /home/ec2-user
  - source: Web4AWS.war
    destination: /home/ec2-user
file_exists_behavior: OVERWRITE
hooks:

  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  install:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  

